'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tb_log_temp
    Public Property ida As Integer
    Public Property log_des As String
    Public Property pvncd As String
    Public Property rgttpcd As String
    Public Property drgtpcd As String
    Public Property rgtno As String
    Public Property log_date As Nullable(Of Date)
    Public Property groupname As String
    Public Property lcnno As String

End Class
