'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_SPC
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property SPC_Th_Name_Medicinal_Product As String
    Public Property SPC_Th_Qualitative_Quantitative_Comp As String
    Public Property SPC_Th_Pharm_Form As String
    Public Property SPC_Th_Clinical_Particular As String
    Public Property SPC_Th_Therapeutic_Indication As String
    Public Property SPC_Th_Posology_Administration As String
    Public Property SPC_Th_Contraindication As String
    Public Property SPC_Th_Special_Warning As String
    Public Property SPC_Th_Interaction As String
    Public Property SPC_Th_Pregnancy_Lactation As String
    Public Property SPC_Th_Ability_Drive_Machine As String
    Public Property SPC_Th_Undesirable_Effect As String
    Public Property SPC_Th_Overdose As String
    Public Property SPC_Th_Pharmaco_Properties As String
    Public Property SPC_Th_Pharmdynamic As String
    Public Property SPC_Th_Pharmacokinetic As String
    Public Property SPC_Th_Preclinical_Safety_Data As String
    Public Property SPC_Th_Pharmaceutical_Particulars As String
    Public Property SPC_Th_Excipients As String
    Public Property SPC_Th_Incompatability As String
    Public Property SPC_Th_Shelf_Life As String
    Public Property SPC_Th_Special_Storage As String
    Public Property SPC_Th_Container As String
    Public Property SPC_Th_MA_Holder As String
    Public Property SPC_Th_MA_Number As String
    Public Property SPC_Th_Date_Approve As String
    Public Property SPC_Th_Date_Revision As String
    Public Property SPC_Eng_Name_Medicinal_Product As String
    Public Property SPC_Eng_Qualitative_Quantitative_Comp As String
    Public Property SPC_Eng_Pharm_Form As String
    Public Property SPC_Eng_Clinical_Particular As String
    Public Property SPC_Eng_Therapeutic_Indication As String
    Public Property SPC_Eng_Posology_Administration As String
    Public Property SPC_Eng_Contraindication As String
    Public Property SPC_Eng_Special_Warning As String
    Public Property SPC_Eng_Interaction As String
    Public Property SPC_Eng_Pregnancy_Lactation As String
    Public Property SPC_Eng_Ability_Drive_Machine As String
    Public Property SPC_Eng_Undesirable_Effect As String
    Public Property SPC_Eng_Overdose As String
    Public Property SPC_Eng_Pharmaco_Properties As String
    Public Property SPC_Eng_Pharmdynamic As String
    Public Property SPC_Eng_Pharmacokinetic As String
    Public Property SPC_Eng_Preclinical_Safety_Data As String
    Public Property SPC_Eng_Pharmaceutical_Particulars As String
    Public Property SPC_Eng_Excipients As String
    Public Property SPC_Eng_Incompatability As String
    Public Property SPC_Eng_Shelf_Life As String
    Public Property SPC_Eng_Special_Storage As String
    Public Property SPC_Eng_Container As String
    Public Property SPC_Eng_MA_Holder As String
    Public Property SPC_Eng_MA_Number As String
    Public Property SPC_Eng_Date_Approve As String
    Public Property SPC_Eng_Date_Revision As String
    Public Property Newcode As String

End Class
