'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_PHARMACY_ESUB
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property lcnsid As String
    Public Property lcntpcd As String
    Public Property lcnno As String
    Public Property lcnno_no As String
    Public Property lcnno_noo As String
    Public Property CITIZEN_AUTHORIZE As String
    Public Property Identify As String
    Public Property typee As String
    Public Property licen As String
    Public Property licen_time As String
    Public Property grannm_lo As String
    Public Property pharmacy_name As String
    Public Property phr As String
    Public Property phr_addrr As String
    Public Property opentime As String
    Public Property Newcode_not As String
    Public Property opentime_pharmacy As String
    Public Property phrno As String
    Public Property phrnm As String
    Public Property lcndtlnm As String
    Public Property cncnm As String
    Public Property appdate As String
    Public Property lmdfdate As String
    Public Property thachngwtnm As String
    Public Property thaamphrnm As String
    Public Property thanm As String
    Public Property thanm_addr As String
    Public Property fk_pharmacy As String
    Public Property chngwtcd As String
    Public Property thachngwtnm_thanm As String
    Public Property amphrcd As String
    Public Property thaamphrnm_thanm As String
    Public Property thmblcd As String
    Public Property thathmblnm_thanm As String
    Public Property fk_ida_dalcn As String

End Class
