'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_PIL
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property PIL_Th_Name_Medicinal_Product As String
    Public Property PIL_Th_Product_Desc As String
    Public Property PIL_Th_Active_Ingradient_Strenght As String
    Public Property PIL_Th_Generic_Name As String
    Public Property PIL_Th_Used_For As String
    Public Property PIL_Th_When_Not_Take As String
    Public Property PIL_Th_Avoid_For_Take As String
    Public Property PIL_Th_How_to_Take As String
    Public Property PIL_Th_When_Miss_Dose As String
    Public Property PIL_Th_Overdose As String
    Public Property PIL_Th_During_Take As String
    Public Property PIL_Th_When_Meet_Doctor_Urgent As String
    Public Property PIL_Th_When_Meet_Doctor As String
    Public Property PIL_Th_How_to_Storage As String
    Public Property PIL_Th_MA_Holder As String
    Public Property PIL_Th_MA_Number As String
    Public Property PIL_Th_Date_Approve As String
    Public Property PIL_Th_Date_Revision As String
    Public Property PIL_Eng_Name_Medicinal_Product As String
    Public Property PIL_Eng_Product_Desc As String
    Public Property PIL_Eng_Active_Ingradient_Strenght As String
    Public Property PIL_Eng_Generic_Name As String
    Public Property PIL_Eng_Used_For As String
    Public Property PIL_Eng_When_Not_Take As String
    Public Property PIL_Eng_Avoid_For_Take As String
    Public Property PIL_Eng_How_to_Take As String
    Public Property PIL_Eng_When_Miss_Dose As String
    Public Property PIL_Eng_Overdose As String
    Public Property PIL_Eng_During_Take As String
    Public Property PIL_Eng_When_Meet_Doctor_Urgent As String
    Public Property PIL_Eng_When_Meet_Doctor As String
    Public Property PIL_Eng_How_to_Storage As String
    Public Property PIL_Eng_MA_Holder As String
    Public Property PIL_Eng_MA_Number As String
    Public Property PIL_Eng_Date_Approve As String
    Public Property PIL_Eng_Date_Revision As String
    Public Property Newcode As String

End Class
