'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_SOURCE_OF_RM
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property iowacd As String
    Public Property iowanm As String
    Public Property phm15dgt As String
    Public Property engdrgnm As String
    Public Property engfrgnnm As String
    Public Property engfrgnnm_addr As String
    Public Property engcntnm As String
    Public Property LICEN_PHM15DGT As String
    Public Property STANDARD_PLACE_STAPLE As String
    Public Property Newcode As String

End Class
