'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_STOWAGR
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property lcnno As String
    Public Property lcnsid As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property keepdesc As String
    Public Property drgchrtha As String
    Public Property useage As String
    Public Property tplow As String
    Public Property tphigh As String
    Public Property drug_age_days As String
    Public Property drug_age_month As String
    Public Property Newcode As String

End Class
