'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_SEARCH_PRODUCT_GROUP_ESUB
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property thargttpnm As String
    Public Property engrgttpnm As String
    Public Property thaclassnm As String
    Public Property engclassnm As String
    Public Property engdrgtpnm As String
    Public Property thakindnm As String
    Public Property engkindnm As String
    Public Property register As String
    Public Property rcvno As String
    Public Property register_rcvno As String
    Public Property lcnsid As String
    Public Property pvnabbr As String
    Public Property lpvncd As String
    Public Property lcntpcd As String
    Public Property lcnno As String
    Public Property lcnno_no As String
    Public Property prefix_thanm As String
    Public Property prefix_licen As String
    Public Property thanm As String
    Public Property thanm_locaion As String
    Public Property licen_loca As String
    Public Property fulladdr As String
    Public Property thaaddr_thanm As String
    Public Property tharoom_thanm As String
    Public Property thafloor_thanm As String
    Public Property thabuilding_thanm As String
    Public Property thasoi_thanm As String
    Public Property tharoad_thanm As String
    Public Property thamu_thanm As String
    Public Property thathmblnm_thanm As String
    Public Property thaamphrnm_thanm As String
    Public Property thachngwtnm_thanm As String
    Public Property zipcode_thanm As String
    Public Property tel_thanm As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property GROUPNAME As String
    Public Property phm15dgt As String
    Public Property CITIZEN_AUTHORIZE As String
    Public Property Identify As String
    Public Property drgperunit As String
    Public Property cntcd As String
    Public Property thadsgnm As String
    Public Property engdsgnm As String
    Public Property ctgthanm As String
    Public Property ctgengnm As String
    Public Property potency As String
    Public Property dsgcd As String
    Public Property ctgcd As String
    Public Property cnccd As String
    Public Property cncnm As String
    Public Property cnccsnm As String
    Public Property appdate As Nullable(Of Date)
    Public Property cncdate As Nullable(Of Date)
    Public Property rcvdate As Nullable(Of Date)
    Public Property rcvdate_T As String
    Public Property appdate_T As String
    Public Property ExpiryDate As String
    Public Property story_edit As String
    Public Property appdate_th As String
    Public Property cncdate_th As String
    Public Property cnsdnm As String
    Public Property engfrgnnm As String
    Public Property engfrgnnm_addr As String
    Public Property rid As String
    Public Property cncdcd As String
    Public Property expdate As Nullable(Of Date)
    Public Property frn_no As String
    Public Property itemno As String
    Public Property Ranking As String
    Public Property typerqt As String
    Public Property Buyers_through As String
    Public Property Buyers_through_cntcd As String
    Public Property Newcode As String
    Public Property Newcode_U As String
    Public Property Newcode_R As String
    Public Property Newcode_not As String
    Public Property register_search As String
    Public Property lmdfdate As Nullable(Of Date)
    Public Property register_search2 As String
    Public Property indication As String
    Public Property funcnm As String
    Public Property IDA_drrgt As Nullable(Of Integer)
    Public Property cncnote As String
    Public Property CER_FORMAT As String
    Public Property engcntnm As String
    Public Property IDA_dh15rqt As Nullable(Of Integer)

End Class
