'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_IOW_EQ
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property register As String
    Public Property CITIZEN_AUTHORIZE As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property flineno As String
    Public Property drgqty As String
    Public Property drgperunit As String
    Public Property drgcdt As String
    Public Property drgcdt_condition As String
    Public Property rid As String
    Public Property elineno As String
    Public Property iowacd As String
    Public Property iowanm As String
    Public Property SinggleContent As String
    Public Property UnitForSinggleContent As String
    Public Property qty As String
    Public Property ConditionContent As String
    Public Property MultiplyNumberStart As String
    Public Property BaseNumberStart As String
    Public Property PowerNumberStart As String
    Public Property MultiplyNumberEND As String
    Public Property BaseNumberEND As String
    Public Property PowerNumberEND As String
    Public Property UnitForRangeContent As String
    Public Property aori As String
    Public Property Newcode As String
    Public Property Newcode_rid As String
    Public Property Newcode_R As String
    Public Property licen_loca As String
    Public Property thaclassnm As String
    Public Property cncnm As String
    Public Property Newcode_rid_eq As String
    Public Property lcnno As String

End Class
