'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_CONTAIN
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property SUBTITLE_SIZE_DRUG As String
    Public Property SMALL_AMOUNT As String
    Public Property SMALL_UNIT As String
    Public Property BIG_UNIT As String
    Public Property BIG_AMOUNT As Nullable(Of Double)
    Public Property MEDIUM_AMOUNT As String
    Public Property MEDIUM_UNIT As String
    Public Property BARCODE As String
    Public Property SUM As String
    Public Property CONRAIN As String
    Public Property STATUS_CONRAIN As String
    Public Property updateDate As Nullable(Of Date)
    Public Property cncdate As Nullable(Of Date)
    Public Property Newcode As String
    Public Property IDA_DRRGT_PACKAGE_DETAIL As Nullable(Of Integer)
    Public Property lcnno As String

End Class
