'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_FRGN
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property lcnsid As String
    Public Property CITIZEN_AUTHORIZE As String
    Public Property lcnno As String
    Public Property thanm As String
    Public Property fulladdr As String
    Public Property engfrgnnm As String
    Public Property engfrgnnm_all As String
    Public Property offengnm As String
    Public Property engcntnm As String
    Public Property funccd As String
    Public Property funcnm As String
    Public Property addr As String
    Public Property room As String
    Public Property floor As String
    Public Property building As String
    Public Property soi As String
    Public Property road As String
    Public Property mu As String
    Public Property district As String
    Public Property subdiv As String
    Public Property Province As String
    Public Property zipcode As String
    Public Property tel As String
    Public Property fax As String
    Public Property Newcode As String
    Public Property Newcode_U As String
    Public Property lcnsid_drpdcin As String
    Public Property lctnmcd_drpdcin As String
    Public Property lctcd_drpdcin As String
    Public Property rid As String

End Class
