'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_PI
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property PI_Th_Name_Medicinal_Product As String
    Public Property PI_Th_Active_Ingradient_Strenght As String
    Public Property PI_Th_Product_Desc As String
    Public Property PI_Th_Pharmacody_Pharmacoki As String
    Public Property PI_Th_Pharmdynamic As String
    Public Property PI_Th_Pharmacokinetic As String
    Public Property PI_Th_Indication As String
    Public Property PI_Th_Recommend_Dose As String
    Public Property PI_Th_Administration As String
    Public Property PI_Th_Contraindication As String
    Public Property PI_Th_Warning_Precaution As String
    Public Property PI_Th_Interaction As String
    Public Property PI_Th_Pregnancy_Lactation As String
    Public Property PI_Th_Undesirable_Effect As String
    Public Property PI_Th_Overdose As String
    Public Property PI_Th_Storage_Condition As String
    Public Property PI_Th_Dose_From_Packaging As String
    Public Property PI_Th_MA_Holder As String
    Public Property PI_Th_MA_Number As String
    Public Property PI_Th_Date_Approve As String
    Public Property PI_Th_Date_Revision As String
    Public Property PI_Eng_Name_Medicinal_Product As String
    Public Property PI_Eng_Active_Ingradient_Strenght As String
    Public Property PI_Eng_Product_Desc As String
    Public Property PI_Eng_Pharmacody_Pharmacoki As String
    Public Property PI_Eng_Pharmdynamic As String
    Public Property PI_Eng_Pharmacokinetic As String
    Public Property PI_Eng_Indication As String
    Public Property PI_Eng_Recommend_Dose As String
    Public Property PI_Eng_Administration As String
    Public Property PI_Eng_Contraindication As String
    Public Property PI_Eng_Warning_Precaution As String
    Public Property PI_Eng_Interaction As String
    Public Property PI_Eng_Pregnancy_Lactation As String
    Public Property PI_Eng_Undesirable_Effect As String
    Public Property PI_Eng_Overdose As String
    Public Property PI_Eng_Storage_Condition As String
    Public Property PI_Eng_Dose_From_Packaging As String
    Public Property PI_Eng_MA_Holder As String
    Public Property PI_Eng_MA_Number As String
    Public Property PI_Eng_Date_Approve As String
    Public Property PI_Eng_Date_Revision As String
    Public Property Newcode As String

End Class
