'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_RECIPE_GROUP
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property lcnno As String
    Public Property lcnsid As String
    Public Property rgtno As String
    Public Property version As String
    Public Property register As String
    Public Property rid As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property atccd As String
    Public Property atcnm As String
    Public Property Newcode As String
    Public Property ATCCDL1 As String
    Public Property ATCCDL2 As String
    Public Property ATCCDL3 As String
    Public Property ATCCDL4 As String
    Public Property ATCCDL5 As String
    Public Property ATCCDL6 As String
    Public Property ATCNML1 As String
    Public Property ATCNML2 As String
    Public Property ATCNML3 As String
    Public Property ATCNML4 As String
    Public Property ATCNML5 As String
    Public Property ATCNML6 As String
    Public Property WHODDDAmount As String
    Public Property WHODDDUnit As String
    Public Property DDD As String
    Public Property UNIT_CD As String
    Public Property Adm_R As String

End Class
