'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_CODE
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property CODE_DL As String
    Public Property CODE_ECTD_IDENIFIER As String
    Public Property TMT_VTM As String
    Public Property TMT_GP As String
    Public Property TMT_GPU As String
    Public Property TMT_TPU As String
    Public Property GTIN As String
    Public Property UNII As String
    Public Property DC24 As String
    Public Property Newcode As String

End Class
