'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_AGENT
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rcvno As String
    Public Property lcnno As String
    Public Property lcnno_no As String
    Public Property identify As String
    Public Property rid As String
    Public Property agent As String
    Public Property addr As String
    Public Property tel As String
    Public Property province As String
    Public Property Newcode As String

End Class
