'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_DOC_PDF
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property PDF_DR_Reg As String
    Public Property PDF_MA_Application As String
    Public Property PDF_Production_Process As String
    Public Property PDF_Product_information As String
    Public Property PDF_Label As String
    Public Property PDF_Amendment As String
    Public Property PDF_Carnofile As String
    Public Property PDF_Drug_Imange As String
    Public Property Newcode As String

End Class
