'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_ANIMAL_CONSUME
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property lcnno As String
    Public Property lcnsid As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property ampartnm As String
    Public Property amlsubnm As String
    Public Property amltpnm As String
    Public Property usetpnm As String
    Public Property stpdrg As String
    Public Property rid As String
    Public Property Newcode As String
    Public Property packuse As String
    Public Property nouse As String

End Class
