'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_STORY_EDIT_HISTORY
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rcvno As String
    Public Property rid As String
    Public Property story_edit_Title As String
    Public Property story_edit_date As Nullable(Of Date)
    Public Property story_edit_appdate As Nullable(Of Date)
    Public Property story_edit_status As String
    Public Property story_edit_desc As String
    Public Property edtcd1 As String
    Public Property edtcd2 As String
    Public Property edtcd3 As String
    Public Property edtcd4 As String
    Public Property edtcd5 As String
    Public Property edtcd6 As String
    Public Property edtcd7 As String
    Public Property edtcd8 As String
    Public Property edtcd9 As String
    Public Property edtcd10 As String
    Public Property edtcd11 As String
    Public Property edtcd12 As String
    Public Property edtcd13 As String
    Public Property edtcd14 As String
    Public Property edtcd15 As String
    Public Property edtcd16 As String
    Public Property edtcd17 As String
    Public Property csnm As String
    Public Property dtl As String
    Public Property Newcode As String
    Public Property lcnno As String

End Class
