'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_DRUG_CONTROL_ANALYZE
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property drgtpcd As String
    Public Property rgttpcd As String
    Public Property rgtno As String
    Public Property rid As String
    Public Property TOPIC_ANALYZE As String
    Public Property METHOD_ANALYZE As String
    Public Property SET_STANDARDS As String
    Public Property REF_STANDARDS As String
    Public Property Newcode As String
    Public Property lcnno As String

End Class
