'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class XML_IOW_TO_DH15_ESUB
    Public Property IDA As Integer
    Public Property pvncd As String
    Public Property pvnabbr As String
    Public Property rcvno As String
    Public Property lcnno As String
    Public Property lcnsid As String
    Public Property rgttpcd As String
    Public Property iowanm As String
    Public Property appdate As String
    Public Property thadrgnm As String
    Public Property engdrgnm As String
    Public Property phm15dgt As String
    Public Property lcntpcd As String
    Public Property drgtpcd As String
    Public Property rid As String
    Public Property cnsdcd As String
    Public Property cncnm As String
    Public Property Newcode As String
    Public Property Newcode_not As String
    Public Property IDA_dh15rqt As Nullable(Of Integer)

End Class
