'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace DRUG_INSERT_DR
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_DRUGSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WS_DRUG
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private DRUG_INSERT_LICENOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_UPDATE_LICENOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_INSERT_DR15OperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_UPDATE_DH15OperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_INSERT_DR15_DEMOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_INSERT_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_UPDATE_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private DRUG_DELETE_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WS_DRUG.My.MySettings.Default.WS_DRUG_WS_DRUGG_WS_DRUG
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event DRUG_INSERT_LICENCompleted As DRUG_INSERT_LICENCompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_UPDATE_LICENCompleted As DRUG_UPDATE_LICENCompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_INSERT_DR15Completed As DRUG_INSERT_DR15CompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_UPDATE_DH15Completed As DRUG_UPDATE_DH15CompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_INSERT_DR15_DEMOCompleted As DRUG_INSERT_DR15_DEMOCompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_INSERT_DRCompleted As DRUG_INSERT_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_UPDATE_DRCompleted As DRUG_UPDATE_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event DRUG_DELETE_DRCompleted As DRUG_DELETE_DRCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_INSERT_LICEN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_INSERT_LICEN(ByVal IDA_dalcn As Integer) As String
            Dim results() As Object = Me.Invoke("DRUG_INSERT_LICEN", New Object() {IDA_dalcn})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_LICENAsync(ByVal IDA_dalcn As Integer)
            Me.DRUG_INSERT_LICENAsync(IDA_dalcn, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_LICENAsync(ByVal IDA_dalcn As Integer, ByVal userState As Object)
            If (Me.DRUG_INSERT_LICENOperationCompleted Is Nothing) Then
                Me.DRUG_INSERT_LICENOperationCompleted = AddressOf Me.OnDRUG_INSERT_LICENOperationCompleted
            End If
            Me.InvokeAsync("DRUG_INSERT_LICEN", New Object() {IDA_dalcn}, Me.DRUG_INSERT_LICENOperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_INSERT_LICENOperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_INSERT_LICENCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_INSERT_LICENCompleted(Me, New DRUG_INSERT_LICENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_UPDATE_LICEN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_UPDATE_LICEN(ByVal IDA_dalcn As Integer) As String
            Dim results() As Object = Me.Invoke("DRUG_UPDATE_LICEN", New Object() {IDA_dalcn})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_UPDATE_LICENAsync(ByVal IDA_dalcn As Integer)
            Me.DRUG_UPDATE_LICENAsync(IDA_dalcn, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_UPDATE_LICENAsync(ByVal IDA_dalcn As Integer, ByVal userState As Object)
            If (Me.DRUG_UPDATE_LICENOperationCompleted Is Nothing) Then
                Me.DRUG_UPDATE_LICENOperationCompleted = AddressOf Me.OnDRUG_UPDATE_LICENOperationCompleted
            End If
            Me.InvokeAsync("DRUG_UPDATE_LICEN", New Object() {IDA_dalcn}, Me.DRUG_UPDATE_LICENOperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_UPDATE_LICENOperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_UPDATE_LICENCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_UPDATE_LICENCompleted(Me, New DRUG_UPDATE_LICENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_INSERT_DR15", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_INSERT_DR15(ByVal IDA_DH15 As Integer) As String
            Dim results() As Object = Me.Invoke("DRUG_INSERT_DR15", New Object() {IDA_DH15})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_DR15Async(ByVal IDA_DH15 As Integer)
            Me.DRUG_INSERT_DR15Async(IDA_DH15, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_DR15Async(ByVal IDA_DH15 As Integer, ByVal userState As Object)
            If (Me.DRUG_INSERT_DR15OperationCompleted Is Nothing) Then
                Me.DRUG_INSERT_DR15OperationCompleted = AddressOf Me.OnDRUG_INSERT_DR15OperationCompleted
            End If
            Me.InvokeAsync("DRUG_INSERT_DR15", New Object() {IDA_DH15}, Me.DRUG_INSERT_DR15OperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_INSERT_DR15OperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_INSERT_DR15CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_INSERT_DR15Completed(Me, New DRUG_INSERT_DR15CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_UPDATE_DH15", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_UPDATE_DH15(ByVal IDA_DH15 As Integer) As String
            Dim results() As Object = Me.Invoke("DRUG_UPDATE_DH15", New Object() {IDA_DH15})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_UPDATE_DH15Async(ByVal IDA_DH15 As Integer)
            Me.DRUG_UPDATE_DH15Async(IDA_DH15, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_UPDATE_DH15Async(ByVal IDA_DH15 As Integer, ByVal userState As Object)
            If (Me.DRUG_UPDATE_DH15OperationCompleted Is Nothing) Then
                Me.DRUG_UPDATE_DH15OperationCompleted = AddressOf Me.OnDRUG_UPDATE_DH15OperationCompleted
            End If
            Me.InvokeAsync("DRUG_UPDATE_DH15", New Object() {IDA_DH15}, Me.DRUG_UPDATE_DH15OperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_UPDATE_DH15OperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_UPDATE_DH15CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_UPDATE_DH15Completed(Me, New DRUG_UPDATE_DH15CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_INSERT_DR15_DEMO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_INSERT_DR15_DEMO(ByVal phm15dgt As String) As String
            Dim results() As Object = Me.Invoke("DRUG_INSERT_DR15_DEMO", New Object() {phm15dgt})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_DR15_DEMOAsync(ByVal phm15dgt As String)
            Me.DRUG_INSERT_DR15_DEMOAsync(phm15dgt, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_DR15_DEMOAsync(ByVal phm15dgt As String, ByVal userState As Object)
            If (Me.DRUG_INSERT_DR15_DEMOOperationCompleted Is Nothing) Then
                Me.DRUG_INSERT_DR15_DEMOOperationCompleted = AddressOf Me.OnDRUG_INSERT_DR15_DEMOOperationCompleted
            End If
            Me.InvokeAsync("DRUG_INSERT_DR15_DEMO", New Object() {phm15dgt}, Me.DRUG_INSERT_DR15_DEMOOperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_INSERT_DR15_DEMOOperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_INSERT_DR15_DEMOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_INSERT_DR15_DEMOCompleted(Me, New DRUG_INSERT_DR15_DEMOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_INSERT_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_INSERT_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String) As String
            Dim results() As Object = Me.Invoke("DRUG_INSERT_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String)
            Me.DRUG_INSERT_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_INSERT_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal userState As Object)
            If (Me.DRUG_INSERT_DROperationCompleted Is Nothing) Then
                Me.DRUG_INSERT_DROperationCompleted = AddressOf Me.OnDRUG_INSERT_DROperationCompleted
            End If
            Me.InvokeAsync("DRUG_INSERT_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno}, Me.DRUG_INSERT_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_INSERT_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_INSERT_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_INSERT_DRCompleted(Me, New DRUG_INSERT_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_UPDATE_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_UPDATE_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String) As String
            Dim results() As Object = Me.Invoke("DRUG_UPDATE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_UPDATE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String)
            Me.DRUG_UPDATE_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_UPDATE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal userState As Object)
            If (Me.DRUG_UPDATE_DROperationCompleted Is Nothing) Then
                Me.DRUG_UPDATE_DROperationCompleted = AddressOf Me.OnDRUG_UPDATE_DROperationCompleted
            End If
            Me.InvokeAsync("DRUG_UPDATE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno}, Me.DRUG_UPDATE_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_UPDATE_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_UPDATE_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_UPDATE_DRCompleted(Me, New DRUG_UPDATE_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DRUG_DELETE_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DRUG_DELETE_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String) As String
            Dim results() As Object = Me.Invoke("DRUG_DELETE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DRUG_DELETE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String)
            Me.DRUG_DELETE_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DRUG_DELETE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal userState As Object)
            If (Me.DRUG_DELETE_DROperationCompleted Is Nothing) Then
                Me.DRUG_DELETE_DROperationCompleted = AddressOf Me.OnDRUG_DELETE_DROperationCompleted
            End If
            Me.InvokeAsync("DRUG_DELETE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno}, Me.DRUG_DELETE_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnDRUG_DELETE_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.DRUG_DELETE_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DRUG_DELETE_DRCompleted(Me, New DRUG_DELETE_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_INSERT_LICENCompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_INSERT_LICENCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_INSERT_LICENCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_UPDATE_LICENCompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_UPDATE_LICENCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_UPDATE_LICENCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_INSERT_DR15CompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_INSERT_DR15CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_INSERT_DR15CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_UPDATE_DH15CompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_UPDATE_DH15CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_UPDATE_DH15CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_INSERT_DR15_DEMOCompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_INSERT_DR15_DEMOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_INSERT_DR15_DEMOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_INSERT_DRCompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_INSERT_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_INSERT_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_UPDATE_DRCompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_UPDATE_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_UPDATE_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")>  _
    Public Delegate Sub DRUG_DELETE_DRCompletedEventHandler(ByVal sender As Object, ByVal e As DRUG_DELETE_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DRUG_DELETE_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
